name=ProtoCentral ADS1292R ECG Library
version=2.0.0
author=ProtoCentral Electronics <support@protocentral.com>
maintainer=ProtoCentral Electronics <protocentral.com>
sentence=Library to read ECG and respiration from the ProtoCentral ADS1292R Shield/Breakout board
paragraph=ADS1292R provides 2-channel 24-bit ADC for ECG and impedance pneumography respiration measurement. This library provides functions to easily read ECG/respiration data and compute heart rate and respiration rate.
category=Sensors
url=https://github.com/Protocentral/protocentral-ads1292r-arduino
architectures=*
includes=protocentral_ads1292r.h,protocentral_ecg_respiration_algorithm.h
